---
- name: Remove Duplicate Config
  file:
    state: absent
    path: /etc/php5/fpm/conf.d/newrelic.ini
  tags:
    - newrelic
    - housekeeping

- name: Configure sysmond | license_key
  lineinfile:
    state: present
    dest: /etc/newrelic/nrsysmond.cfg
    regexp: '^#* *license_key'
    line: 'license_key={{ newrelic_license }}'
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic

- name: Configure sysmond | proxy
  lineinfile:
    state: present
    dest: /etc/newrelic/nrsysmond.cfg
    regexp: '^#* *proxy'
    line: "proxy={{ newrelic_proxy_address }}:{{ newrelic_proxy_port }}"
  when: newrelic_proxy_required
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic

- name: Copy PHP APM Template
  command: cp /usr/lib/newrelic-php5/scripts/newrelic.ini.template /etc/php5/mods-available/newrelic.ini
  when: newrelic_php_apm_enabled

- name: Configure PHP APM | newrelic.license
  lineinfile:
    state: present
    dest: /etc/php5/mods-available/newrelic.ini
    regexp: '^;* *newrelic\.license'
    line: 'newrelic.license = "{{ newrelic_license }}"'
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php

- name: Configure PHP APM | newrelic.appname
  lineinfile:
    state: present
    dest: /etc/php5/mods-available/newrelic.ini
    regexp: '^;* *newrelic\.appname'
    line: 'newrelic.appname = "{{ newrelic_appname }}"'
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php

- name: Configure PHP APM | newrelic.daemon.proxy
  lineinfile:
    state: present
    dest: /etc/php5/mods-available/newrelic.ini
    regexp: '^;* *newrelic\.daemon\.proxy'
    line: "newrelic.daemon.proxy = \"{{ newrelic_proxy_address }}:{{ newrelic_proxy_port }}\""
  notify: Reload Service | php5-fpm
  when: 'newrelic_php_apm_enabled and newrelic_proxy_required'
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php

- name: Enable PHP APM Extension
  command: php5enmod newrelic
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
